In [2]:
import requests
import pandas as pd
from datetime import datetime


headers = {
    "X-RapidAPI-Key": "4005866697msh2b2c979bf694ec1p1cef3fjsne0259089faa3",
    "X-RapidAPI-Host": "cricbuzz-cricket.p.rapidapi.com"
}

url = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/live"

response = requests.get(url, headers=headers)
data = response.json()

In [80]:
from sqlalchemy import create_engine

server = 'DESKTOP-B66UO89\\SQLEXPRESS'
database = 'CricketDB'

connection_string = (
    "mssql+pyodbc://@DESKTOP-B66UO89\\SQLEXPRESS/CricketDB?"
    "driver=ODBC+Driver+17+for+SQL+Server&"
    "trusted_connection=yes"
)

In [6]:
## Get live match data (1st page)

In [3]:
rows = []

for mt in data.get('typeMatches', []):
    for series in mt.get('seriesMatches', []):
        wrapper = series.get('seriesAdWrapper')
        if wrapper:
            for match in wrapper.get('matches', []):
                info = match['matchInfo']
                rows.append({
                    "match_id": info.get("matchId"),
                    "series_name": info.get("seriesName"),
                    "format": info.get("matchFormat"),
                    "team1_name": info["team1"]["teamName"],
                    "team2_name": info["team2"]["teamName"],
                    "status": info.get("status"),
                    "venue_name": info["venueInfo"]["city"],
                    "startdate": datetime.fromtimestamp(int(info['seriesStartDt'])/1000),
                    "enddate": datetime.fromtimestamp(int(info['seriesEndDt'])/1000)
                })
matches_live = pd.DataFrame(rows)

In [22]:
matches_live.to_sql('matches_live', con=connection_string, if_exists='replace', index=False)

9

In [5]:
matches_live

,match_id,series_name,format,team1_name,team2_name,status,venue_name,startdate,enddate
0,148503,"Sweden tour of Indonesia, 2026",T20,Sweden,Indonesia,Sweden opt to bat,Bali,2026-04-07 05:30:00,2026-04-15 05:30:00
1,148492,"Sweden tour of Indonesia, 2026",T20,Sweden,Indonesia,Indonesia won by 4 wkts,Bali,2026-04-07 05:30:00,2026-04-15 05:30:00
2,142098,County Championship Division One 2026,TEST,Hampshire,Yorkshire,Day 3: Stumps - Yorkshire need 361 runs,Leeds,2026-04-03 05:30:00,2026-09-29 05:30:00
3,142109,County Championship Division One 2026,TEST,Surrey,Leicestershire,Day 3: Stumps - Leicestershire lead by 171 runs,London,2026-04-03 05:30:00,2026-09-29 05:30:00
4,142087,County Championship Division One 2026,TEST,Warwickshire,Sussex,Day 3: Stumps - Sussex need 94 runs,Hove,2026-04-03 05:30:00,2026-09-29 05:30:00
5,142120,County Championship Division One 2026,TEST,Nottinghamshire,Glamorgan,Day 3: Stumps - Glamorgan need 346 runs,Nottingham,2026-04-03 05:30:00,2026-09-29 05:30:00
6,142803,County Championship Division Two 2026,TEST,Northamptonshire,Kent,Day 3: Stumps - Kent trail by 344 runs,Canterbury,2026-04-03 05:30:00,2026-09-29 05:30:00
7,142814,County Championship Division Two 2026,TEST,Lancashire,Derbyshire,Day 3: Stumps - Lancashire lead by 124 runs,Manchester,2026-04-03 05:30:00,2026-09-29 05:30:00
8,153039,"Women's Under-19 Tri-Series in Australia, 2026",T20,Australia Women U19,Sri Lanka Women U19,Sri Lanka Women U19 won by 4 wkts,Gold Coast,2026-04-06 05:30:00,2026-04-20 05:30:00

## 2nd top_scores_details

In [82]:
all_matches_players = []

match_ids = matches_live["match_id"]

for mid in match_ids:
    score_url = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{mid}/scard"
    res = requests.get(score_url, headers=headers)

    if res.status_code == 200:
        score_data = res.json()

        for inning in score_data.get('scorecard', []):
                    # -------------------------
            # 🏏 BATSMEN DATA
            # -------------------------
            for b in inning.get('batsman', []):
                all_matches_players.append({
                    "player_id": b.get('id'),
                    "name": b.get('name'),
                    "role": "batsman",
                    "match_id": mid,
                    "runs": b.get('runs'),
                    "balls": b.get('balls'),
                    "fours": b.get('fours'),
                    "sixes": b.get('sixes'),
                    "strike_rate": b.get('strkrate'),
                    "dismissal": b.get('outdec'),
                    "innings": inning.get('inningsid'),
                    "team_wickets": team_wickets,
                    "team_overs": team_overs,
        
                    })
        
                    # -------------------------
                    # 🎯 BOWLERS DATA (IMPORTANT)
                    # -------------------------
            for bowler in inning.get('bowler', []):
                all_matches_players.append({
                    "player_id": bowler.get('id'),
                    "name": bowler.get('name'),
                    "role": "bowler",
                    "match_id": mid,
                    "overs": bowler.get('overs'),
                    "maidens": bowler.get('maidens'),
                    "runs_conceded": bowler.get('runs'),
                    "wickets": bowler.get('wickets'),
                    "economy": bowler.get('economy'),
                    "innings": inning.get('inningsid'),
                    "team_wickets": team_wickets,
                    "team_overs": team_overs,
                        }) 
    else:
        print(f"Failed for match {mid}: {res.status_code}")

In [83]:
players = pd.DataFrame(all_matches_players)

In [84]:
players

,player_id,name,role,match_id,runs,balls,fours,sixes,strike_rate,dismissal,innings,team_wickets,team_overs,overs,maidens,runs_conceded,wickets,economy
0,28649,Imal Zuwak,batsman,148503,5.0,3.0,1.0,0.0,166.67,b Gaurav Tiwari,1,6,19.3,NaN,NaN,NaN,NaN,NaN
1,44504,Ajay Mundra,batsman,148503,6.0,3.0,0.0,1.0,200,c Gede Priandana b Ferdinando Banunaek,1,6,19.3,NaN,NaN,NaN,NaN,NaN
2,1456633,Awais Ahmad,batsman,148503,0.0,1.0,0.0,0.0,0,c Danilson Hawoe b Ferdinando Banunaek,1,6,19.3,NaN,NaN,NaN,NaN,NaN
3,1461378,Yatharth Chauhan,batsman,148503,32.0,28.0,4.0,1.0,114.29,c Gaurav Tiwari b Kadek Gamantika,1,6,19.3,NaN,NaN,NaN,NaN,NaN
4,26386,Wynand Boshoff,batsman,148503,0.0,3.0,0.0,0.0,0,b Gaurav Tiwari,1,6,19.3,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
442,1470437,Aurora Mavros,bowler,153039,NaN,NaN,NaN,NaN,NaN,NaN,2,6,19.3,3,0.0,15.0,0.0,5
443,1463782,Filippa Suesee,bowler,153039,NaN,NaN,NaN,NaN,NaN,NaN,2,6,19.3,4,0.0,18.0,3.0,4.5
444,1448981,Tegan Williamson,bowler,153039,NaN,NaN,NaN,NaN,NaN,NaN,2,6,19.3,4,0.0,19.0,0.0,4.8
445,1463848,Emily Powell,bowler,153039,NaN,NaN,NaN,NaN,NaN,NaN,2,6,19.3,1,0.0,5.0,0.0,5
446,1454743,Ayaka Kato-Stafford,bowler,153039,NaN,NaN,NaN,NaN,NaN,NaN,2,6,19.3,1,0.0,4.0,0.0,4

In [85]:
players.to_sql('players', con=connection_string, if_exists='replace', index=False)

99

In [87]:
top_runs_per_match = (players.sort_values(["match_id", "runs"], ascending=[True, False]).groupby("match_id").first().reset_index()[["match_id", "name", "runs"]])

In [88]:
Highest_score_per_match = (players.sort_values(["match_id", "runs"], ascending=[True, False]).groupby("match_id").first().reset_index()[["match_id", "name", "runs","balls"]])

In [89]:
top_strikerate_per_match = (players.sort_values(["match_id", "strike_rate","runs"], ascending=[True, False,False]).groupby("match_id").first().reset_index()[["match_id", "name", "strike_rate","runs"]])

In [90]:
most_wickets_per_match = (players.sort_values(["match_id", "team_wickets"], ascending=[True, False]).groupby("match_id").first().reset_index()[["match_id", "name", "wickets","overs"]])

In [93]:
top_runs_per_match

   match_id                  name   runs
0    142087          Robert Yates   90.0
1    142098             Ben Brown  103.0
2    142109           Jamie Smith  166.0
3    142120            Joe Clarke  136.0
4    142803          Luke Procter  261.0
5    142814         Marcus Harris  125.0
6    148492  Kavin Neeraj Chaddha   60.0
7    148503           Saeed Ahmed   38.0
8    153039      Pramudi Methsara   21.0

In [92]:
top_strikerate_per_match

   match_id               name strike_rate   runs
0    142087        James Coles       91.67   11.0
1    142098          Ben Brown        94.5  103.0
2    142109       Dan Lawrence       86.11   31.0
3    142120     Kyle Verreynne       93.33   14.0
4    142803     Tawanda Muyeye       84.21   48.0
5    142814           Anuj Dal       95.45   21.0
6    148492       Advait Dhabe        87.5   21.0
7    148503  Apriliandi Rahayu      366.67   11.0
8    153039     Indira Panelli        87.5    7.0

In [7]:
# import requests
# import pandas as pd
# from datetime import datetime

# headers = {
#     "X-RapidAPI-Key": "39902b1d99mshd7ca7a0ef0d9f74p1b0117jsnf7edb4c7a10b",
#     "X-RapidAPI-Host": "cricbuzz-cricket.p.rapidapi.com"
# }

# url1 = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/recent"

# responser = requests.get(url1, headers=headers)
# datar = responser.json()

## SQL questions

In [9]:
# import pandas as pd

# def flatten_match(datar):
#     matches = datar.get("typeMatches", [])

#     rows = []

#     for mt in matches:
#         match_type = mt.get("matchType")

#         for series in mt.get("seriesMatches", []):
#             series_info = series.get("seriesAdWrapper", {})

#             for match in series_info.get("matches", []):

#                 m = match.get("matchInfo", {})
#                 score = match.get("matchScore", {})

#                 row = {
#                     # 🏏 match info
#                     "match_id": m.get("matchId"),
#                     "series_id": m.get("seriesId"),
#                     "series_name": m.get("seriesName"),
#                     "match_desc": m.get("matchDesc"),
#                     "match_format": m.get("matchFormat"),
#                     "start_date": datetime.fromtimestamp(int(m.get("startDate"))/1000),
#                     "end_date": datetime.fromtimestamp(int(m.get("endDate"))/1000),
#                     "state": m.get("state"),
#                     "status": m.get("status"),

#                     # 🏟️ teams
#                     "team1_id": m.get("team1", {}).get("teamId"),
#                     "team1_name": m.get("team1", {}).get("teamName"),
#                     "team1_short": m.get("team1", {}).get("teamSName"),

#                     "team2_id": m.get("team2", {}).get("teamId"),
#                     "team2_name": m.get("team2", {}).get("teamName"),
#                     "team2_short": m.get("team2", {}).get("teamSName"),

#                     # 📊 scores
#                     "team1_runs": score.get("team1Score", {}).get("inngs1", {}).get("runs"),
#                     "team1_wkts": score.get("team1Score", {}).get("inngs1", {}).get("wickets"),
#                     "team1_overs": score.get("team1Score", {}).get("inngs1", {}).get("overs"),

#                     "team2_runs": score.get("team2Score", {}).get("inngs1", {}).get("runs"),
#                     "team2_wkts": score.get("team2Score", {}).get("inngs1", {}).get("wickets"),
#                     "team2_overs": score.get("team2Score", {}).get("inngs1", {}).get("overs"),

#                     # 📍 venue
#                     "venue_id": m.get("venueInfo", {}).get("id"),
#                     "ground": m.get("venueInfo", {}).get("ground"),
#                     "city": m.get("venueInfo", {}).get("city"),

#                     # 🧠 result
#                     "result": m.get("status")
#                 }

#                 rows.append(row)

#     return pd.DataFrame(rows)

In [10]:
df = flatten_match(datar)

In [11]:
df

,match_id,series_id,series_name,match_desc,match_format,start_date,end_date,state,status,team1_id,...,team1_runs,team1_wkts,team1_overs,team2_runs,team2_wkts,team2_overs,venue_id,ground,city,result
0,151517,7572,ICC Cricket World Cup League Two 2023-27,97th Match,ODI,2026-04-12 13:00:00,2026-04-12 21:00:00,Complete,Scotland won by 7 wkts,161,...,198,10,48.6,199,3,37.6,1438021,Namibia Cricket Ground,Windhoek,Scotland won by 7 wkts
1,151506,7572,ICC Cricket World Cup League Two 2023-27,96th Match,ODI,2026-04-10 13:00:00,2026-04-10 21:00:00,Complete,Namibia won by 1 wkt,304,...,218,9,49.6,223,9,49.3,363,Wanderers Cricket Ground,Windhoek,Namibia won by 1 wkt
2,148503,11652,"Sweden tour of Indonesia, 2026",8th T20I,T20,2026-04-13 11:30:00,2026-04-13 15:00:00,Complete,Sweden won by 18 runs,534,...,166,8,19.6,148,10,18.2,1179,Udayana Cricket Ground,Bali,Sweden won by 18 runs
3,148492,11652,"Sweden tour of Indonesia, 2026",7th T20I,T20,2026-04-13 07:00:00,2026-04-13 10:30:00,Complete,Indonesia won by 4 wkts,534,...,145,9,19.6,148,6,17.4,1179,Udayana Cricket Ground,Bali,Indonesia won by 4 wkts
4,148481,11652,"Sweden tour of Indonesia, 2026",6th T20I,T20,2026-04-11 11:30:00,2026-04-11 15:00:00,Complete,Sweden won by 87 runs,534,...,170,6,19.6,83,10,15.2,1179,Udayana Cricket Ground,Bali,Sweden won by 87 runs
5,148470,11652,"Sweden tour of Indonesia, 2026",5th T20I,T20,2026-04-11 07:00:00,2026-04-11 10:30:00,Complete,Sweden won by 5 wkts,566,...,165,5,19.6,166,5,18.6,1179,Udayana Cricket Ground,Bali,Sweden won by 5 wkts
6,148459,11652,"Sweden tour of Indonesia, 2026",4th T20I,T20,2026-04-09 11:30:00,2026-04-09 15:00:00,Complete,Sweden won by 10 runs,534,...,164,7,19.6,154,9,19.6,1179,Udayana Cricket Ground,Bali,Sweden won by 10 runs
7,148874,11704,"Scotland tour of Namibia, 2026",1st T20I,T20,2026-04-15 17:30:00,2026-04-15 21:00:00,Complete,Scotland won by 7 wkts,161,...,159,7,19.6,160,3,18.5,1438021,Namibia Cricket Ground,Windhoek,Scotland won by 7 wkts
8,150285,11740,"Portugal T20I Tri-Series, 2026",Final,T20,2026-04-09 19:00:00,2026-04-09 22:30:00,Complete,Portugal won by 30 runs,596,...,183,6,19.6,153,10,18.6,1528,Santarem Cricket Ground,Albergaria,Portugal won by 30 runs
9,150274,11740,"Portugal T20I Tri-Series, 2026",9th Match,T20,2026-04-09 14:30:00,2026-04-09 18:00:00,Complete,France won by 4 wkts,1027,...,111,10,18.5,112,6,17.1,1528,Santarem Cricket Ground,Albergaria,France won by 4 wkts
10,151774,9241,Indian Premier League 2026,23rd Match,T20,2026-04-15 19:30:00,2026-04-15 23:00:00,Complete,Royal Challengers Bengaluru won by 5 wkts,966,...,146,10,19.6,149,5,15.1,27,M.Chinnaswamy Stadium,Bengaluru,Royal Challengers Bengaluru won by 5 wkts
11,151763,9241,Indian Premier League 2026,22nd Match,T20,2026-04-14 19:30:00,2026-04-14 23:00:00,Complete,Chennai Super Kings won by 32 runs,58,...,192,5,19.6,160,7,19.6,11,MA Chidambaram Stadium,Chennai,Chennai Super Kings won by 32 runs
12,151752,9241,Indian Premier League 2026,21st Match,T20,2026-04-13 19:30:00,2026-04-13 23:00:00,Complete,Sunrisers Hyderabad won by 57 runs,255,...,216,6,19.6,159,10,18.6,80,Rajiv Gandhi International Stadium,Hyderabad,Sunrisers Hyderabad won by 57 runs
13,149812,9241,Indian Premier League 2026,20th Match,T20,2026-04-12 19:30:00,2026-04-12 23:00:00,Complete,Royal Challengers Bengaluru won by 18 runs,59,...,240,4,19.6,222,5,19.6,81,Wankhede Stadium,Mumbai,Royal Challengers Bengaluru won by 18 runs
14,149801,9241,Indian Premier League 2026,19th Match,T20,2026-04-12 15:30:00,2026-04-12 19:00:00,Complete,Gujarat Titans won by 7 wkts,966,...,164,8,19.6,165,3,18.4,485,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Gujarat Titans won by 7 wkts
15,149790,9241,Indian Premier League 2026,18th Match,T20,2026-04-11 19:30:00,2026-04-11 23:00:00,Complete,Chennai Super Kings won by 23 runs,58,...,212,2,19.6,189,10,19.6,11,MA Chidambaram Stadium,Chennai,Chennai Super Kings won by 23 runs
16,149779,9241,Indian Premier League 2026,17th Match,T20,2026-04-11 15:30:00,2026-04-11 19:00:00,Complete,Punjab Kings won by 6 wkts,255,...,219,6,19.6,223,4,18.5,851,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,Punjab Kings won by 6 wkts
17,149768,9241,Indian Premier League 2026,16th Match,T20,2026-04-10 19:30:00,2026-04-10 23:00:00,Complete,Rajasthan Royals won by 6 wkts,59,...,201,8,19.6,202,4,17.6,380,Barsapara Cricket Stadium,Guwahati,Rajasthan Royals won by 6 wkts
18,149757,9241,Indian Premier League 2026,15th Match,T20,2026-04-09 19:30:00,2026-04-09 23:00:00,Complete,Lucknow Super Giants won by 3 wkts,63,...,181,4,19.6,182,7,19.6,31,Eden Gardens,Kolkata,Lucknow Super Giants won by 3 wkts
19,149182,11537,Pakistan Super League 2026,23rd Match,T20,2026-04-15 19:30:00,2026-04-15 23:00:00,Complete,Peshawar Zalmi won by 8 wkts,331,...,154,10,19.6,156,2,18.3,24,National Stadium,Karachi,Peshawar Zalmi won by 8 wkts
20,149171,11537,Pakistan Super League 2026,22nd Match,T20,2026-04-13 19:30:00,2026-04-13 23:00:00,Complete,Peshawar Zalmi won by 24 runs,334,...,196,6,19.6,172,8,19.6,24,National Stadium,Karachi,Peshawar Zalmi won by 24 runs
21,149160,11537,Pakistan Super League 2026,21st Match,T20,2026-04-12 19:30:00,2026-04-12 23:00:00,Complete,Hyderabad Kingsmen won by 6 wkts,330,...,153,9,19.6,157,4,18.1,24,National Stadium,Karachi,Hyderabad Kingsmen won by 6 wkts
22,149149,11537,Pakistan Super League 2026,20th Match,T20,2026-04-11 19:30:00,2026-04-11 23:00:00,Complete,Hyderabad Kingsmen won by 4 wkts,332,...,188,8,19.6,189,6,19.1,24,National Stadium,Karachi,Hyderabad Kingsmen won by 4 wkts
23,149138,11537,Pakistan Super League 2026,19th Match,T20,2026-04-11 15:00:00,2026-04-11 18:30:00,Complete,Peshawar Zalmi won by 76 runs,334,...,173,7,19.6,97,10,16.6,24,National Stadium,Karachi,Peshawar Zalmi won by 76 runs
24,149127,11537,Pakistan Super League 2026,18th Match,T20,2026-04-10 19:30:00,2026-04-10 23:00:00,Complete,Quetta Gladiators won by 61 runs,331,...,182,6,19.6,121,10,17.3,24,National Stadium,Karachi,Quetta Gladiators won by 61 runs
25,149116,11537,Pakistan Super League 2026,17th Match,T20,2026-04-09 19:30:00,2026-04-09 23:00:00,Complete,Peshawar Zalmi won by 159 runs,334,...,246,3,19.6,87,10,16.1,24,National Stadium,Karachi,Peshawar Zalmi won by 159 runs
26,149105,11537,Pakistan Super League 2026,16th Match,T20,2026-04-09 15:00:00,2026-04-09 18:30:00,Complete,Islamabad United won by 9 wkts,333,...,100,10,18.3,104,1,10.2,24,National Stadium,Karachi,Islamabad United won by 9 wkts
27,142087,11408,County Championship Division One 2026,7th Match,TEST,2026-04-10 15:30:00,2026-04-13 22:30:00,Complete,Sussex won by 5 wkts,140,...,267,10,79.4,204,10,50.3,292,County Ground,Hove,Sussex won by 5 wkts
28,142120,11408,County Championship Division One 2026,10th Match,TEST,2026-04-10 15:30:00,2026-04-13 22:30:00,Complete,Nottinghamshire won by 192 runs,139,...,279,10,63.4,113,10,47.6,18,Trent Bridge,Nottingham,Nottinghamshire won by 192 runs
29,142098,11408,County Championship Division One 2026,8th Match,TEST,2026-04-10 15:30:00,2026-04-13 22:30:00,Complete,Hampshire won by 214 runs,153,...,251,10,69.1,177,10,65.4,66,Headingley,Leeds,Hampshire won by 214 runs
30,142076,11408,County Championship Division One 2026,6th Match,TEST,2026-04-10 15:30:00,2026-04-13 22:30:00,Complete,Somerset won by 10 wkts,152,...,149,10,50.6,348,10,92.3,118,County Ground,Chelmsford,Somerset won by 10 wkts
31,142109,11408,County Championship Division One 2026,9th Match,TEST,2026-04-10 15:30:00,2026-04-13 22:30:00,Complete,Match drawn,148,...,520,10,113.2,691,10,170.4,12,Kennington Oval,London,Match drawn
32,150316,11749,"New Zealand A tour of Sri Lanka, 2026",3rd unofficial ODI,ODI,2026-04-11 10:00:00,2026-04-11 18:00:00,Complete,Sri Lanka A won by 4 wkts,80,...,302,7,49.6,303,6,46.2,255,Mahinda Rajapaksa International Stadium,Hambantota,Sri Lanka A won by 4 wkts
33,142803,11416,County Championship Division Two 2026,7th Match,TEST,2026-04-10 15:30:00,2026-04-13 22:30:00,Complete,Match drawn,142,...,684,2,133.3,178,10,64.1,67,St Lawrence Ground,Canterbury,Match drawn
34,142791,11416,County Championship Division Two 2026,5th Match,TEST,2026-04-10 15:30:00,2026-04-13 22:30:00,Complete,Worcestershire won by 57 runs,147,...,191,10,54.5,183,10,63.1,19,Lord's,London,Worcestershire won by 57 runs
35,142814,11416,County Championship Division Two 2026,8th Match,TEST,2026-04-10 15:30:00,2026-04-13 22:30:00,Complete,Lancashire won by 29 runs,143,...,351,10,91.2,374,10,114.3,65,Emirates Old Trafford,Manchester,Lancashire won by 29 runs
36,142802,11416,County Championship Division Two 2026,6th Match,TEST,2026-04-10 15:30:00,2026-04-13 22:30:00,Complete,Durham won by an innings and 225 runs,141,...,605,5,113.6,175,10,48.3,63,County Ground,Bristol,Durham won by an innings and 225 runs
37,153050,11766,"Women's Under-19 Tri-Series in Australia, 2026",4th unofficial T20I,T20,2026-04-15 11:30:00,2026-04-15 15:00:00,Complete,Australia Women U19 won by 9 wkts,1398,...,100,9,19.6,103,1,15.4,732,Ian Healy Oval,Brisbane,Australia Women U19 won by 9 wkts
38,153039,11766,"Women's Under-19 Tri-Series in Australia, 2026",3rd unofficial T20I,T20,2026-04-13 09:00:00,2026-04-13 12:30:00,Complete,Sri Lanka Women U19 won by 4 wkts,1328,...,91,9,19.6,92,6,19.3,1438034,Bill Pippen Oval,Gold Coast,Sri Lanka Women U19 won by 4 wkts
39,153010,11766,"Women's Under-19 Tri-Series in Australia, 2026",2nd unofficial T20I,T20,2026-04-12 09:00:00,2026-04-12 12:30:00,Complete,Sri Lanka Women U19 won by 8 runs,1361,...,136,6,19.6,128,10,19.2,1438034,Bill Pippen Oval,Gold Coast,Sri Lanka Women U19 won by 8 runs
40,152999,11766,"Women's Under-19 Tri-Series in Australia, 2026",1st unofficial T20I,T20,2026-04-11 09:00:00,2026-04-11 12:30:00,Complete,Australia Women U19 won by 9 wkts,1398,...,114,10,18.6,115,1,16.1,1438034,Bill Pippen Oval,Gold Coast,Australia Women U19 won by 9 wkts
41,153154,11726,"Kalahari Women's T20I Tournament, 2026",Final,T20,2026-04-11 17:45:00,2026-04-11 21:15:00,Complete,Brazil Women won by 3 wkts,488,...,37,10,11.1,38,7,9.5,1305,Botswana Cricket Association Oval 1,Gaborone,Brazil Women won by 3 wkts
42,153143,11726,"Kalahari Women's T20I Tournament, 2026",3rd Place Play-off,T20,2026-04-11 17:30:00,2026-04-11 21:00:00,Complete,Malawi Women won by 1 wkt,493,...,91,8,19.6,92,9,17.6,1312,Botswana Cricket Association Oval 2,Gaborone,Malawi Women won by 1 wkt
43,153132,11726,"Kalahari Women's T20I Tournament, 2026",Plate - Match 3,T20,2026-04-11 13:00:00,2026-04-11 16:30:00,Complete,Lesotho Women won by 48 runs,499,...,96,7,19.6,48,3,19.6,1312,Botswana Cricket Association Oval 2,Gaborone,Lesotho Women won by 48 runs
44,153123,11726,"Kalahari Women's T20I Tournament, 2026",Super League - Match 3,T20,2026-04-11 12:45:00,2026-04-11 16:15:00,Complete,Botswana Women won by 81 runs,488,...,139,4,19.6,58,10,16.4,1305,Botswana Cricket Association Oval 1,Gaborone,Botswana Women won by 81 runs
45,153112,11726,"Kalahari Women's T20I Tournament, 2026",Plate - Match 2,T20,2026-04-10 17:45:00,2026-04-10 21:15:00,Complete,Malawi Women won by 53 runs,495,...,86,10,19.6,33,10,13.6,1312,Botswana Cricket Association Oval 2,Gaborone,Malawi Women won by 53 runs
46,153101,11726,"Kalahari Women's T20I Tournament, 2026",Super League - Match 2,T20,2026-04-10 17:30:00,2026-04-10 21:00:00,Complete,Brazil Women won by 9 wkts,493,...,19,10,7.3,20,1,2.1,1305,Botswana Cricket Association Oval 1,Gaborone,Brazil Women won by 9 wkts
47,153094,11726,"Kalahari Women's T20I Tournament, 2026",Plate - Match 1,T20,2026-04-10 13:00:00,2026-04-10 16:30:00,Complete,Malawi Women won by 9 wkts,499,...,40,10,17.4,41,1,7.3,1312,Botswana Cricket Association Oval 2,Gaborone,Malawi Women won by 9 wkts
48,153083,11726,"Kalahari Women's T20I Tournament, 2026",Super League - Match 1,T20,2026-04-10 12:45:00,2026-04-10 16:15:00,Complete,Brazil Women won by 8 wkts,488,...,85,7,19.6,86,2,11.6,1305,Botswana Cricket Association Oval 1,Gaborone,Brazil Women won by 8 wkts
49,149999,11726,"Kalahari Women's T20I Tournament, 2026",15th Match,T20,2026-04-09 17:30:00,2026-04-09 21:00:00,Complete,Malawi Women won by 5 wkts,494,...,54,6,19.6,55,5,10.2,1305,Botswana Cricket Association Oval 1,Gaborone,Malawi Women won by 5 wkts
50,149988,11726,"Kalahari Women's T20I Tournament, 2026",14th Match,T20,2026-04-09 13:00:00,2026-04-09 16:30:00,Complete,Brazil Women won by 189 runs,491,...,202,8,19.6,13,10,6.2,1312,Botswana Cricket Association Oval 2,Gaborone,Brazil Women won by 189 runs
51,149977,11726,"Kalahari Women's T20I Tournament, 2026",13th Match,T20,2026-04-09 12:45:00,2026-04-09 16:15:00,Complete,Malawi Women won by 7 wkts,493,...,60,10,14.5,61,3,12.3,1305,Botswana Cricket Association Oval 1,Gaborone,Malawi Women won by 7 wkts

In [20]:
df.columns

Index(['match_id', 'series_id', 'series_name', 'match_desc', 'match_format',
       'start_date', 'end_date', 'state', 'status', 'team1_id', 'team1_name',
       'team1_short', 'team2_id', 'team2_name', 'team2_short', 'team1_runs',
       'team1_wkts', 'team1_overs', 'team2_runs', 'team2_wkts', 'team2_overs',
       'venue_id', 'ground', 'city', 'result'],
      dtype='object')

## Matches

In [97]:
matches = df[['match_desc','match_id','team1_name','team2_name','venue_id','ground','city','match_format','start_date']].drop_duplicates(ignore_index=True)

In [99]:
matches.to_sql('matches', con=connection_string, if_exists='replace', index=False)

52

## Series

In [91]:
series = df[['series_id', 'series_name','match_format','start_date','end_date']].drop_duplicates(ignore_index=True)

In [94]:
series.to_sql('series', con=connection_string, if_exists='replace', index=False)

45

## Venues

In [41]:
venues = []

venueId = df["venue_id"].dropna().unique()


headers = {
    "X-RapidAPI-Key": "1b7742aaf8mshce1201037d8658ap158288jsn90656ad61c14",
    "X-RapidAPI-Host": "cricbuzz-cricket.p.rapidapi.com"
}

for vid in venueId:
    url = f"https://cricbuzz-cricket.p.rapidapi.com/venues/v1/{int(vid)}"
    response = requests.get(url, headers=headers)
    data = response.json()
    venues.append({"venue_id": int(vid),
                    "venue_name": data.get("ground"),
                   "city": data.get("city"),
                    "country": data.get("country"),
                   "capacity": data.get("capacity")})

In [ ]:
import json
import os

CACHE_FILE = "venues_cache.json"

# load cache
if os.path.exists(CACHE_FILE):
    with open(CACHE_FILE, "r") as f:
        cache = json.load(f)
else:
    cache = {}

def get_venue(vid):
    if str(vid) in cache:
        return cache[str(vid)]  # ✅ no API call

    url = f"https://cricbuzz-cricket.p.rapidapi.com/venues/get-info/venues/v1/{vid}"
    res = requests.get(url, headers=headers)

    if res.status_code == 200:
        data = res.json()
        cache[str(vid)] = data

        # save immediately
        with open(CACHE_FILE, "w") as f:
            json.dump(cache, f)

        return data

In [43]:
venues_details = pd.DataFrame(venues)

In [81]:
venues_details.to_sql('venues', con=connection_string, if_exists='replace', index=False)

27

In [44]:
venues_details

,venue_id,venue_name,city,country,capacity
0,1438021,Namibia Cricket Ground,Windhoek,Namibia,None
1,363,Wanderers Cricket Ground,Windhoek,Namibia,None
2,1179,Udayana Cricket Ground,Bali,Indonesia,None
3,1528,Santarem Cricket Ground,Albergaria,Portugal,None
4,27,M.Chinnaswamy Stadium,Bengaluru,India,"40,000"
5,11,MA Chidambaram Stadium,Chennai,India,50000
6,80,Rajiv Gandhi International Stadium,Hyderabad,India,38000
7,81,Wankhede Stadium,Mumbai,India,"33,000"
8,485,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,India,50000
9,851,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,India,38000
10,380,Barsapara Cricket Stadium,Guwahati,India,40000
11,31,Eden Gardens,Kolkata,India,63000
12,24,National Stadium,Karachi,Pakistan,34228
13,292,County Ground,Hove,England,4000
14,18,Trent Bridge,Nottingham,England,"15,350 (to be 17,000)"
15,66,Headingley,Leeds,England,17000
16,118,County Ground,Chelmsford,England,6500
17,12,Kennington Oval,London,England,23500
18,255,Mahinda Rajapaksa International Stadium,Hambantota,Sri Lanka,34300
19,67,St Lawrence Ground,Canterbury,England,15000
20,19,Lord's,London,England,30000
21,65,Emirates Old Trafford,Manchester,England,19000
22,63,County Ground,Bristol,England,"7000 (15,000 ODIs)"
23,732,Ian Healy Oval,Brisbane,Australia,None
24,1438034,Bill Pippen Oval,Gold Coast,Australia,None
25,1305,Botswana Cricket Association Oval 1,Gaborone,Botswana,None
26,1312,Botswana Cricket Association Oval 2,Gaborone,Botswana,None

## Players

In [50]:
players_list = []
match_ids = df["match_id"]

for mid in match_ids:
    score_url = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{mid}/scard"
    res = requests.get(score_url, headers=headers)
    score_data = res.json()

    for inning in score_data.get('scorecard', []):
                    # -------------------------
            # 🏏 BATSMEN DATA
            # -------------------------
            for b in inning.get('batsman', []):
                players_list.append({
                    "player_id": b.get('id')})

            # -------------------------
            # 🏏 BOWLER DATA
            # -------------------------
            for bowler in inning.get('bowler', []):
                players_list.append({
                    "player_id": bowler.get('id')})

In [52]:
df1 = pd.DataFrame(players_list)

In [75]:
df1['player_id'].dropna().nunique()

686

In [76]:
players = []

player_ids = df1["player_id"].dropna().unique()

for pid in player_ids:
    score_url = f"https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/{int(pid)}"
    res = requests.get(score_url, headers=headers)
    d = res.json()
    players.append({"id": d.get("id"),
            "name": d.get("name"),
            "role": d.get("role"),
            "batting": d.get("bat"),
            "bowling": d.get("bowl"),
            "country": d.get("birthPlace")})

KeyboardInterrupt:

In [63]:
score_url = f"https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/6635"
res = requests.get(score_url, headers=headers)
d = res.json()

In [123]:
from datetime import datetime, timedelta

last_30_days = datetime.now() - timedelta(days=30)

result = df[df["start_date"] >= last_30_days]

# sort recent first
result = result.sort_values(by="start_date", ascending=False)

result

,match_id,series_id,series_name,match_desc,match_format,start_date,end_date,state,status,team1_id,...,team1_runs,team1_wkts,team1_overs,team2_runs,team2_wkts,team2_overs,venue_id,ground,city,result
50,153039,11766,"Women's Under-19 Tri-Series in Australia, 2026",3rd unofficial T20I,T20,2026-04-13 09:00:00,2026-04-13 12:30:00,Complete,Sri Lanka Women U19 won by 4 wkts,1328,...,91.0,9.0,19.6,92.0,6.0,19.3,1438034,Bill Pippen Oval,Gold Coast,Sri Lanka Women U19 won by 4 wkts
4,148492,11652,"Sweden tour of Indonesia, 2026",7th T20I,T20,2026-04-13 07:00:00,2026-04-13 10:30:00,Complete,Indonesia won by 4 wkts,534,...,145.0,9.0,19.6,148.0,6.0,17.4,1179,Udayana Cricket Ground,Bali,Indonesia won by 4 wkts
28,149160,11537,Pakistan Super League 2026,21st Match,T20,2026-04-12 19:30:00,2026-04-12 23:00:00,Complete,Hyderabad Kingsmen won by 6 wkts,330,...,153.0,9.0,19.6,157.0,4.0,18.1,24,National Stadium,Karachi,Hyderabad Kingsmen won by 6 wkts
19,149812,9241,Indian Premier League 2026,20th Match,T20,2026-04-12 19:30:00,2026-04-12 23:00:00,Complete,Royal Challengers Bengaluru won by 18 runs,59,...,240.0,4.0,19.6,222.0,5.0,19.6,81,Wankhede Stadium,Mumbai,Royal Challengers Bengaluru won by 18 runs
20,149801,9241,Indian Premier League 2026,19th Match,T20,2026-04-12 15:30:00,2026-04-12 19:00:00,Complete,Gujarat Titans won by 7 wkts,966,...,164.0,8.0,19.6,165.0,3.0,18.4,485,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow,Gujarat Titans won by 7 wkts
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41,142043,11408,County Championship Division One 2026,3rd Match,TEST,2026-04-03 15:30:00,2026-04-06 22:30:00,Complete,Match drawn,149,...,302.0,10.0,120.3,226.0,10.0,60.2,62,Sophia Gardens,Cardiff,Match drawn
40,142065,11408,County Championship Division One 2026,5th Match,TEST,2026-04-03 15:30:00,2026-04-06 22:30:00,Complete,Match drawn,119,...,347.0,10.0,103.5,338.0,10.0,103.2,223,The Cooper Associates County Ground,Taunton,Match drawn
38,142054,11408,County Championship Division One 2026,4th Match,TEST,2026-04-03 15:30:00,2026-04-06 22:30:00,Complete,Sussex won by 222 runs,41,...,361.0,10.0,89.5,245.0,10.0,64.6,222,Grace Road,Leicester,Sussex won by 222 runs
37,142030,11408,County Championship Division One 2026,1st Match,TEST,2026-04-03 15:30:00,2026-04-06 22:30:00,Complete,Match drawn,148,...,328.0,10.0,95.1,544.0,10.0,128.3,20,Edgbaston,Birmingham,Match drawn
39,142041,11408,County Championship Division One 2026,2nd Match,TEST,2026-04-03 15:30:00,2026-04-06 22:30:00,Complete,Essex won by an innings and 137 runs,152,...,461.0,7.0,138.3,156.0,10.0,48.3,21,The Rose Bowl,Southampton,Essex won by an innings and 137 runs

In [125]:
series_url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/international"

res = requests.get(series_url, headers=headers)
series_data = res.json()

In [158]:
series = series_data.get("seriesMapProto", [])

row1 = []

for mt in series:
    series_type = mt.get("date")
    for j in mt.get("series", []):
        z = {"Date": series_type,
        "series_id": j.get("id"),
        "series_name": j.get("name"),
        "series_startdate": j.get("startDt"),
        "series_enddate": j.get("endDt")}
        
    row1.append(z)

In [159]:
series = series_data.get("seriesMapProto", [])

In [160]:
df2 = pd.DataFrame(row1)

In [68]:
df_series

,date,series_id,series_name,start_date,end_date
0,FEBRUARY 2024,7572,ICC Cricket World Cup League Two 2023-27,1707955200000,1830038400000
1,APRIL 2026,11652,"Sweden tour of Indonesia, 2026",1775520000000,1776038400000
2,APRIL 2026,11704,"Scotland tour of Namibia, 2026",1776211200000,1776470400000
3,APRIL 2026,11733,"New Zealand tour of Bangladesh, 2026",1776384000000,1777680000000
4,APRIL 2026,12012,"Luxembourg tour of France, 2026",1776988800000,1777161600000
5,MAY 2026,12034,"Gibraltar tour of Malta, 2026",1778112000000,1778284800000
6,MAY 2026,12004,ICC Men's T20 World Cup East Asia Pacific Qual...,1778198400000,1779062400000
7,JUNE 2026,11946,Sri Lanka tour of West Indies 2026,1780444800000,1783382400000
8,JUNE 2026,10559,"New Zealand tour of England, 2026",1780531200000,1782691200000
9,JUNE 2026,11641,Afghanistan tour of India 2026,1780704000000,1781913600000
10,JUNE 2026,11814,"India tour of Ireland, 2026",1782432000000,1782604800000
11,JUNE 2026,10532,"India tour of England, 2026",1782864000000,1784419200000
12,JULY 2026,11957,"New Zealand tour of West Indies, 2026",1783728000000,1784592000000
13,JULY 2026,11968,"Pakistan tour of West Indies, 2026",1784332800000,1785974400000
14,JULY 2026,11991,India tour of Zimbabwe 2026,1784764800000,1785024000000
15,AUGUST 2026,11825,"Afghanistan tour of Ireland, 2026",1785888000000,1786665600000
16,AUGUST 2026,11630,"Bangladesh tour of Australia, 2026",1786579200000,1787702400000
17,AUGUST 2026,10565,Pakistan tour of England 2026,1787097600000,1788912000000
18,SEPTEMBER 2026,11997,Australia tour of Zimbabwe 2026,1789430400000,1789862400000
19,SEPTEMBER 2026,10576,"Sri Lanka tour of England, 2026",1789430400000,1790467200000
20,SEPTEMBER 2026,11595,"Australia tour of South Africa, 2026",1790208000000,1793404800000
21,SEPTEMBER 2026,11902,"West Indies tour of India, 2026",1790467200000,1792195200000
22,NOVEMBER 2026,11876,"England tour of Australia, 2026",1794528000000,1796169600000
23,NOVEMBER 2026,11606,"Bangladesh tour of South Africa, 2026",1794700800000,1797120000000
24,DECEMBER 2026,11858,"New Zealand tour of Australia, 2026-27",1796774400000,1799366400000
25,DECEMBER 2026,11913,"Sri Lanka tour of India, 2026",1797120000000,1798329600000
26,DECEMBER 2026,11612,"England tour of South Africa, 2026-27",1797465600000,1799971200000
27,JANUARY 2027,11924,"Zimbabwe tour of India, 2027",1798934400000,1799452800000
28,JANUARY 2027,11935,"Australia tour of India, 2027",1800489600000,1804032000000
29,MARCH 2027,11883,"Australia vs England, 150th Anniversary Test M...",1804723200000,1805068800000

In [161]:
df2

,Date,series_id,series_name,series_startdate,series_enddate
0,FEBRUARY 2024,7572,ICC Cricket World Cup League Two 2023-27,1707955200000,1806364800000
1,APRIL 2026,12012,"Luxembourg tour of France, 2026",1776988800000,1777161600000
2,MAY 2026,12004,ICC Men's T20 World Cup East Asia Pacific Qual...,1778198400000,1779062400000
3,JUNE 2026,10532,"India tour of England, 2026",1782864000000,1784419200000
4,JULY 2026,11991,India tour of Zimbabwe 2026,1784764800000,1785024000000
5,AUGUST 2026,10565,Pakistan tour of England 2026,1787097600000,1788912000000
6,SEPTEMBER 2026,11902,"West Indies tour of India, 2026",1790467200000,1792195200000
7,NOVEMBER 2026,11606,"Bangladesh tour of South Africa, 2026",1794700800000,1797120000000
8,DECEMBER 2026,11612,"England tour of South Africa, 2026-27",1797465600000,1799971200000
9,JANUARY 2027,11935,"Australia tour of India, 2027",1800489600000,1804032000000
10,MARCH 2027,11883,"Australia vs England, 150th Anniversary Test M...",1804723200000,1805068800000

In [5]:
import requests
import pandas as pd
from datetime import datetime


headers = {
    "X-RapidAPI-Key": "4005866697msh2b2c979bf694ec1p1cef3fjsne0259089faa3",
    "X-RapidAPI-Host": "cricbuzz-cricket.p.rapidapi.com"
}

# Step 1: Get all series
series_url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/international"
response = requests.get(series_url, headers=headers)
data = response.json()

series_map = data.get("seriesMapProto", {})

Total Series: 11
Empty DataFrame
Columns: []
Index: []
Total Matches: 0

In [70]:
import time

series_rows = []
for item in series_map:
    date = item.get("date")
    
    for series in item.get("series", []):
        series_rows.append({
            "date": date,
            "series_id": series.get("id"),
            "series_name": series.get("name"),
            "start_date": series.get("startDt"),
            "end_date": series.get("endDt")
        })

df_series = pd.DataFrame(series_rows)

Total Series: 30
Empty DataFrame
Columns: []
Index: []
Total Matches: 0

In [76]:
import requests
import pandas as pd

headers = {
    "X-RapidAPI-Key": "4005866697msh2b2c979bf694ec1p1cef3fjsne0259089faa3",
    "X-RapidAPI-Host": "cricbuzz-cricket.p.rapidapi.com"
}

url = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/recent"

response = requests.get(url, headers=headers)
data = response.json()

recent_matches = []

for match_type in data.get("typeMatches", []):
    for series in match_type.get("seriesMatches", []):
        
        series_info = series.get("seriesAdWrapper", {})
        series_id = series_info.get("seriesId")
        series_name = series_info.get("seriesName")
        
        for match in series_info.get("matches", []):
            info = match.get("matchInfo", {})
            
            recent_matches.append({
                "series_id": series_id,
                "series_name_recent": series_name,
                "match_id": info.get("matchId"),
                "team1": info.get("team1", {}).get("teamName"),
                "team2": info.get("team2", {}).get("teamName"),
                "match_format": info.get("matchFormat"),
                "status": info.get("status")
            })

df_recent = pd.DataFrame(recent_matches)

print(df_recent.head())

Empty DataFrame
Columns: []
Index: []

In [77]:
data

{'message': 'You have exceeded the MONTHLY quota for Requests on your current plan, BASIC. Upgrade your plan at https://rapidapi.com/cricketapilive/api/cricbuzz-cricket'}